version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookshop
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: password123_imt
    restart: always
    networks:
      - honeypot_network

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always
    networks:
      - honeypot_network

networks:
  honeypot_network:
    driver: bridge
